docs: update readme logo
asyncapi/diff pull request #91
Opened 2022-03-23 15:50 UTC by aayushmau5

**Description**

- Update the `README.md` logo/banner

**Related issue(s)**
Resolves https://github.com/asyncapi/diff/issues/89

2022-03-24 07:37 UTC, derberg approved these changes

2022-03-24 07:39 UTC, derberg commented
closed and reopened to see if we can trigger handing ci

2022-03-24 14:20 UTC, magicmatatjahu requested changes

2022-03-24 14:20 UTC, magicmatatjahu commented on README.md
> +[![AsyncAPI Banner and Logo](/assets/logo.png)](https://www.asyncapi.com)
```suggestion
[![AsyncAPI Diff](/assets/logo.png)](https://www.asyncapi.com)
```

2022-03-24 15:55 UTC, mcturco commented on README.md
> +[![AsyncAPI Banner and Logo](/assets/logo.png)](https://www.asyncapi.com)
+ 1 on this suggestion

2022-03-25 10:16 UTC, magicmatatjahu approved these changes

2022-03-25 10:16 UTC, magicmatatjahu commented
/rtm

2022-03-25 11:29 UTC, onbit-uchenik approved these changes

2022-03-25 12:02 UTC, merged